
[functions.send-recruitment-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-recruitment-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-recruitment-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-recruitment-email/*.html" ]

[functions.send-contact-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-contact-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-contact-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-contact-email/*.html" ]

[functions.create-payment-order]
enabled = true
verify_jwt = false
import_map = "./functions/create-payment-order/deno.json"
entrypoint = "./functions/create-payment-order/index.ts"

[functions.verify-payment]
enabled = true
verify_jwt = false
import_map = "./functions/verify-payment/deno.json"
entrypoint = "./functions/verify-payment/index.ts"

[functions.send-otp-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-otp-email/deno.json"
entrypoint = "./functions/send-otp-email/index.ts"

[functions.verify-otp]
enabled = true
verify_jwt = false
import_map = "./functions/verify-otp/deno.json"
entrypoint = "./functions/verify-otp/index.ts"

[functions.send-training-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-training-email/deno.json"
entrypoint = "./functions/send-training-email/index.ts"
