project_id = "Rareminds-Website"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[auth.sms]
enable_signup = false
enable_confirmations = false
max_frequency = "5s"

[auth.external.apple]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
redirect_uri = ""
url = ""
skip_nonce_check = false

[auth.external.azure]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_AZURE_SECRET)"
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_BITBUCKET_SECRET)"

[auth.external.discord]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_SECRET)"

[auth.external.facebook]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_FACEBOOK_SECRET)"

[auth.external.figma]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_FIGMA_SECRET)"

[auth.external.github]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET)"

[auth.external.gitlab]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_GITLAB_SECRET)"
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"
skip_nonce_check = false

[auth.external.keycloak]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_KEYCLOAK_SECRET)"
url = ""

[auth.external.linkedin_oidc]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_LINKEDIN_OIDC_SECRET)"

[auth.external.notion]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_NOTION_SECRET)"

[auth.external.twitch]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_TWITCH_SECRET)"

[auth.external.twitter]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_TWITTER_SECRET)"

[auth.external.slack_oidc]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_SLACK_OIDC_SECRET)"

[auth.external.spotify]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_SPOTIFY_SECRET)"

[auth.external.workos]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_WORKOS_SECRET)"
url = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_ZOOM_SECRET)"

[analytics]
enabled = false
port = 54327
backend = "postgres"

[db.seed]
sql_paths = ['./seed.sql', './seed_remote.sql', './seed_event_sections.sql']

[functions.send-recruitment-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-recruitment-email/deno.json"
entrypoint = "./functions/send-recruitment-email/index.ts"

[functions.send-contact-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-contact-email/deno.json"
entrypoint = "./functions/send-contact-email/index.ts"

[functions.create-payment-order]
enabled = true
verify_jwt = false
import_map = "./functions/create-payment-order/deno.json"
entrypoint = "./functions/create-payment-order/index.ts"

[functions.verify-payment]
enabled = true
verify_jwt = false
import_map = "./functions/verify-payment/deno.json"
entrypoint = "./functions/verify-payment/index.ts"

[functions.send-otp-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-otp-email/deno.json"
entrypoint = "./functions/send-otp-email/index.ts"

[functions.verify-otp]
enabled = true
verify_jwt = false
import_map = "./functions/verify-otp/deno.json"
entrypoint = "./functions/verify-otp/index.ts"

[functions.send-training-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-training-email/deno.json"
entrypoint = "./functions/send-training-email/index.ts"
