-- =====================================================
-- PROGRAMS SEED DATA (Generated from Frontend Source)
-- =====================================================
-- This file contains program and section data extracted from SuccessStorieslistings.ts
-- Frontend data is the source of truth for content
-- Insert programs into programs table
INSERT INTO programs (id, title, slug, program_type, location, date, status, image_url, banner_url, short_description, display_order, is_active) VALUES
(uuid_generate_v4(), 'Acharya', 'acharya', 'College', 'Karnataka', '2023-05-01', 'Completed', '/academy/Projects/acharya-institute-of-technology.jpg', '/academy/Projects/acharya-institute-of-technology.jpg', 'Rareminds trained 700+ MBA, MCA, and Physiotherapy students in communication and placement skills, boosting interview confidence and job readiness.', 1, true),
(uuid_generate_v4(), 'PES', 'pes', 'University', 'Karnataka', '2023-07-01', 'Active', '/academy/Projects/pes.png', '/academy/Projects/pes.png', 'The Rareminds Bootcamp at PES Engineering College, Mandya delivered a 45-hour hands-on web development program, transforming students into confident, industry-ready developers', 2, true),
(uuid_generate_v4(), 'VELS', 'vels', 'University', 'Tamil Nadu', '2024-03-01', 'Completed', '/academy/Projects/Vels.jpg', '/academy/Projects/Vels.jpg', 'Rareminds delivered project-based training at VELS University, bridging classroom learning with real-world skills for first-year students.', 3, true),
(uuid_generate_v4(), 'Visvesvaraya Technological University', 'visvesvaraya-technological-university', 'University', 'Karnataka', '2025-01-01', 'Active', '/academy/Projects/vtu.png', '/academy/Projects/vtu.png', 'Rareminds partners with Visvesvaraya Technological University to deliver industry-relevant training programs that enhance technical skills and improve student employability across Karnataka.', 4, true),
(uuid_generate_v4(), 'DSATM', 'dsatm', 'College', 'Karnataka', '2019-10-01', 'Completed', '/academy/Projects/dsce.jpg', '/academy/Projects/dsce.jpg', 'Rareminds partnered with DSATM to deliver career-focused training that equipped students with technical and soft skills for professional success.', 5, true),
(uuid_generate_v4(), 'BLDEA', 'bldea', 'Organization', 'Karnataka', '2023-11-01', 'Completed', '/academy/Projects/BLDEA.png', '/academy/Projects/BLDEA.png', 'Rareminds conducted a 3-day intensive program for 200+ BLDEA teachers, delivering hands-on, NEP-aligned training to strengthen pedagogy, mindset, and classroom effectiveness.', 6, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO programs (id, title, slug, program_type, location, date, status, image_url, banner_url, short_description, display_order, is_active) VALUES
(uuid_generate_v4(), 'Naan Mudhalvan 2024 Upskilling Program (Powered by Rareminds)', 'naan-mudhalvan-2024', 'Naan Mudhalvan', 'Tamil Nadu', '2024-07-01', 'Active', '/academy/Projects/nanmudhalvan.jpg', '/academy/Projects/image 2.png', 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.', 7, true),
(uuid_generate_v4(), 'Naan Mudhalvan 2023 Upskilling Program (Powered by Rareminds)', 'naan-mudhalvan-2023', 'Naan Mudhalvan', 'Tamil Nadu', '2023-01-01', 'Completed', '/academy/Projects/nanmudhalvan.jpg', '/academy/Projects/image 2.png', 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.', 8, true),
(uuid_generate_v4(), 'Naan Mudhalvan 4th sem 2025 Upskilling Program (Powered by Rareminds)', 'naan-mudhalvan-4th-sem-2025', 'Naan Mudhalvan', 'Tamil Nadu', '2025-01-01', 'Active', '/academy/Projects/nanmudhalvan.jpg', '/academy/Projects/image 2.png', 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.', 9, true),
(uuid_generate_v4(), 'Naan Mudhalvan 6th sem 2025 Upskilling Program (Powered by Rareminds)', 'naan-mudhalvan-6th-sem-2025', 'Naan Mudhalvan', 'Tamil Nadu', '2025-01-01', 'Active', '/academy/Projects/nanmudhalvan.jpg', '/academy/Projects/image 2.png', 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.', 10, true),
(uuid_generate_v4(), 'Naan Mudhalvan 2025 Upskilling Program (Powered by Rareminds)', 'naan-mudhalvan-2025', 'Naan Mudhalvan', 'Tamil Nadu', '2025-07-01', 'Active', '/academy/Projects/nanmudhalvan.jpg', '/academy/Projects/image 2.png', 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.', 11, true)
ON CONFLICT (slug) DO NOTHING;
-- Add Government Body programs to programs table
INSERT INTO programs (id, title, slug, program_type, location, date, status, image_url, banner_url, short_description, display_order, is_active) VALUES
(uuid_generate_v4(), 'Tripura', 'tripura', 'Government Body', 'Tripura', '2024-01-01', 'Completed', '/academy/Projects/tripura.png', '/academy/Projects/tripura.png', 'Rareminds trained 200 overseas candidates via a CEO-led intensive, boosting interview confidence and global readiness in line with Tripura Skill Development Mission.', 12, true),
(uuid_generate_v4(), 'TNSDC ITI (Spoken English)', 'tnsdc-iti-spoken-english', 'Government Body', 'Tamil Nadu', '2024-02-01', 'Completed', '/academy/Projects/tnsdc.png', '/academy/Projects/tnsdc.png', 'Rareminds partnered with TNSDC to train government hostel students in English, communication, and confidence.', 13, true),
(uuid_generate_v4(), 'TNSDC Schools', 'tnsdc-schools', 'Government Body', 'Tamil Nadu', '2024-04-01', 'Completed', '/academy/Projects/tnsdc.png', '/academy/Projects/tnsdc.png', 'Rareminds delivered a 7-day training across 121 schools, empowering 1,974 students with employability skills.', 14, true),
(uuid_generate_v4(), 'AICTE', 'aicte', 'Government Body', 'Pan India', '2025-01-01', 'Completed', '/academy/Projects/aicte.png', '/academy/Projects/aicte.png', 'Rareminds partnered with All India Council for Technical Education to deliver industry-focused, experiential programs that build job-ready skills and confidence', 15, true),
(uuid_generate_v4(), 'KSDC', 'ksdc', 'Government Body', 'Karnataka', '2025-01-01', 'In Progress', '/academy/Projects/ksdc.png', '/academy/Projects/ksdc.png', 'Rareminds collaborates with Karnataka Skill Development Corporation to deliver comprehensive skill development programs that enhance employability and bridge the skill gap in Karnataka.', 16, true),
(uuid_generate_v4(), 'Global International School', 'global-international-school', 'School', 'Karnataka', '2023-11-01', 'Completed', '/academy/Projects/gtis-logo.png', '/academy/Projects/gtis-logo.png', 'Rareminds bridged gaps in traditional teacher training by delivering hands-on, NEP-aligned programs that equipped educators with practical skills, modern tools, and learner-centric strategies.', 17, true)
ON CONFLICT (slug) DO NOTHING;

-- =====================================================
-- PROGRAM SECTIONS SEED DATA (COLLEGE CATEGORY ONLY)
-- =====================================================

-- Insert program sections for Acharya (College)
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'acharya'), 'header', 'From Campus Conversations to Corporate Confidence', 'Great careers begin with clear communication. At Acharya Institute, Bangalore, the gap between technical skills and professional readiness was evident among students preparing for the job market. Recognizing this, Rareminds was brought in to bridge the communication gap and empower students with the skills they need to thrive in the real world.'),
((SELECT id FROM programs WHERE slug = 'acharya'), 'introduction', 'Introduction', 'In May 2022–2023, Rareminds conducted a high-impact 5-day Business Communication course for over 700 students across the Physiotherapy, MBA, and MCA departments. The sessions were tailored to enhance industry-specific communication, presentation skills, and professional behavior. This was followed by pre-placement readiness training for 120 MBA and 233 MCA students in 2024, building confidence right before they stepped into the hiring ecosystem.'),
((SELECT id FROM programs WHERE slug = 'acharya'), 'modules', 'Modules Covered', 'Industry-Oriented Communication Frameworks. Email and Business Writing Best Practices. Presentation and Interview Skills. Group Discussions and Personal Branding. Corporate Etiquette and Workplace Readiness.'),
((SELECT id FROM programs WHERE slug = 'acharya'), 'approaches', 'Multiple Approaches', 'Interactive Simulations & Mock Interviews. Real-time Feedback Loops. Resume Labs and Elevator Pitch Practice. Peer Critique Sessions.'),
((SELECT id FROM programs WHERE slug = 'acharya'), 'impact', 'Outcomes and Impact', '85% of students reported increased clarity and confidence in job interviews. Campus recruiters highlighted better articulation and professionalism in placement rounds. MBA & MCA placement coordinators reported smoother pre-placement processes.'),
((SELECT id FROM programs WHERE slug = 'acharya'), 'strategic_alignment', 'Strategic Alignment with Acharya''s Vision', 'This initiative aligned seamlessly with Acharya Institute''s goals of: Enhancing Industry Readiness Among Graduates. Elevating Communication as a Core Career Skill. Enabling Seamless Transition from Classroom to Corporate. Strengthening Placement Outcomes through Holistic Training.'),
((SELECT id FROM programs WHERE slug = 'acharya'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'acharya'), 'conclusion', 'Crafting Communicators, Not Just Candidates', 'At Acharya Institute, Rareminds went beyond basic communication training. We helped students shape their voice, articulate their value, and enter the professional world with poise and purpose. The impact was clear: sharper skills, stronger confidence, and a generation ready to make their mark.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Insert program sections for PES (College)
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'pes'), 'introduction', 'Introduction', 'The Rareminds Bootcamp at PES Engineering College, Mandya, contributed to transform aspiring engineers into confident, industry-ready developers. Through an intensive, 45-hour Web Development Bootcamp, we bridged the classroom-to-career gap with a hands-on, real-world coding experience that left students skilled, motivated, and ready for the digital future.'),
((SELECT id FROM programs WHERE slug = 'pes'), 'about', 'About the Program', 'Web Development Bootcamp: From July 24th to 29th, 2023, Rareminds delivered a comprehensive Web Development Bootcamp focused on Full Stack skills. The program immersed students in practical learning, from HTML, CSS, and JavaScript to React, backend integration, APIs, and deployment techniques.

Learning Approach: Designed around active problem-solving, teamwork, and real-time feedback, this initiative gave students the tools to think like developers and build like professionals.'),
((SELECT id FROM programs WHERE slug = 'pes'), 'impact', 'Key Outcomes & Impact', 'Trained 100+ students through immersive bootcamp sessions combining technical depth and collaborative learning. 70% of students built fully functional web applications from scratch. 90% actively participated in hands-on coding exercises and real-time problem-solving. 100% expressed confidence in building, securing, and deploying full-stack web applications. 85% reported improved critical thinking and collaboration skills applicable across technical and non-technical settings. 92% experienced growth in communication and teamwork through pair programming and group challenges. 88% said they could now clearly articulate technical ideas, preparing them for interviews and presentations.'),
((SELECT id FROM programs WHERE slug = 'pes'), 'strategic_alignment', 'Strategic Alignment with PES College Goals', 'This initiative reinforced PES Engineering College''s commitment to: Skill-Based, Industry-Ready Learning. NAAC and NIRF Enhancement through Outcome-Focused Programs. Innovation and Startup Culture among Students. Improved Placement Readiness with Practical Tech Exposure. NEP 2020 Alignment through experiential, future-focused education.'),
((SELECT id FROM programs WHERE slug = 'pes'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'pes'), 'conclusion', 'Turning Coders into Creators', 'At PES Engineering College, Rareminds didn''t just teach programming — we built a culture of innovation, confidence, and readiness. By empowering students to develop real solutions, communicate effectively, and collaborate as tech professionals, we helped transform the campus into a launchpad for tomorrow''s digital leaders.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Insert program sections for VELS (College)
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'vels'), 'introduction', 'Introduction', 'Rareminds training programs at VELS University to reshape technical education for first-year students, delivering high-impact, project-based training in emerging technologies. The initiative successfully bridged classroom learning with real-world application, equipping students with future-ready skills and confidence for the evolving digital workplace.'),
((SELECT id FROM programs WHERE slug = 'vels'), 'about', 'About the Program', 'Industrial Metaverse: Two 45-hour experiential training programs were delivered to undergraduate students as part of this collaboration. This program combined cutting-edge tools like VR and AI with hands-on projects, enabling students to simulate real-world environments from day one.

Web Full Stack Development: Two 45-hour experiential training programs were delivered to undergraduate students as part of this collaboration. This program combined the MERN stack with hands-on projects, enabling students to code, build, and deploy real-world applications from day one.'),
((SELECT id FROM programs WHERE slug = 'vels'), 'impact', 'Key Outcomes & Impact', '200+ students trained through structured, mentor-led sessions. 90% of participants built deployable full-stack applications using modern frameworks and platforms. 95% of students rated the training 8/10 or higher for content, delivery, and usefulness. 85% reported improved career confidence, especially in applying skills to internships and interviews. Students demonstrated enhanced critical thinking and teamwork, with active participation in all sessions. Positive institutional feedback from faculty who observed increased engagement, curiosity, and practical understanding.'),
((SELECT id FROM programs WHERE slug = 'vels'), 'strategic_alignment', 'Strategic Alignment with VELS University Goals', 'This initiative supported key institutional objectives such as: NAAC & NIRF enhancement through experiential learning and tech integration. Improved employability outcomes via skill-based, industry-aligned content. Curriculum innovation, aligned with NEP 2020 and industry expectations. Higher student engagement contributes to improved retention and satisfaction.'),
((SELECT id FROM programs WHERE slug = 'vels'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'vels'), 'conclusion', 'Conclusion', 'This successful collaboration with VELS University demonstrated Rareminds'' ability to deliver measurable outcomes, transform student learning, and align with institutional goals. By turning classrooms into innovation labs, we empowered students to become creators, not just consumers of technology.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Insert program sections for DSATM (College)
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'dsatm'), 'introduction', 'The Real-World Leap: How DSATM Students Gained a Competitive Edge', 'Rareminds has been a long-standing training partner for DSATM, driving student employability through curated, career-oriented workshops. By integrating both technical and soft skill components, these programs empowered engineering and management students with practical tools to thrive in professional settings.'),
((SELECT id FROM programs WHERE slug = 'dsatm'), 'about', 'About the Program', 'MBA Students: 5-Day Advanced Excel Workshop (Sept–Oct 2019). Focused on business analytics and reporting through practical spreadsheet applications.

Non-Teaching Staff: MS Office & Email Etiquette (Feb 2019) – 3-day session introducing essential digital tools and workplace communication. Advanced Excel, Time Management & Personal Branding via Social Media (July 2019) – A holistic 3-day program to enhance productivity and professional presence.

Civil Engineering Students: Day 1: Surveying & geospatial analysis using Total Station & GIS. Day 2: Construction Project Management tools and methodologies (PERT, CPM, EVM). Day 3: BIM, Risk Management, and digital modeling exposure. Participation: 60 students.'),
((SELECT id FROM programs WHERE slug = 'dsatm'), 'impact', 'Key Outcomes & Impact', '100+ participants trained across engineering, management, and staff categories. Practical exposure to tools like MS Excel, Total Station, and BIM. Positive feedback across sessions for delivery, content relevance, and applicability. Strengthened cross-functional competencies like project planning, digital communication, and personal branding. Programs led by industry experts ensured real-world context and engagement.'),
((SELECT id FROM programs WHERE slug = 'dsatm'), 'strategic_alignment', 'Strategic Alignment with DSATM Goals', 'This engagement supported DSATM''s mission to: Enhance student employability through skill-based learning. Encourage interdisciplinary exposure and industry linkage. Build digital and workplace readiness across academic and administrative stakeholders. Foster a continuous learning culture in both student and staff communities.'),
((SELECT id FROM programs WHERE slug = 'dsatm'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'dsatm'), 'conclusion', 'Conclusion', 'Rareminds'' collaboration with DSATM highlights how focused, practical training can drive institutional growth, individual confidence, and long-term career success. By delivering real-world learning across multiple touchpoints, this partnership continues to shape a more future-ready, skilled campus ecosystem.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Note: Visvesvaraya Technological University has no sections in frontend data, so no program_sections entries are added for it.
-- =====================================================
-- BLDEA PROGRAM SECTIONS
-- =====================================================

-- Insert program sections for BLDEA
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'bldea'), 'introduction', 'Elevating Everyday Teaching into Transformational Practice', 'Building great schools begins with investing in great teachers. BLDEA Schools in Karnataka recognized the need to move beyond routine training and focus on structured, high-impact development. Teachers were navigating classrooms without consistent support in pedagogy, communication, emotional intelligence, and NEP-aligned practices. A unified approach was necessary to ensure that professional growth was intact across levels and that the student engagement remained consistent, meaningful, and aligned with evolving learning needs. Rareminds delivered a concentrated, practice-based model focused on both mindset and method. Rareminds conducted a 3-day intensive program for over 200 teachers across the BLDEA network. Sessions were led by 5 master trainers and grounded in real classroom challenges.'),
((SELECT id FROM programs WHERE slug = 'bldea'), 'modules', 'Modules Covered', 'NEP 2020 Alignment and Classroom Planning. Assessment Frameworks and Tools. Inclusive Teaching Practices. Empathy in Education. Positive Engagement and Student Motivation.'),
((SELECT id FROM programs WHERE slug = 'bldea'), 'approaches', 'Multiple Approaches', 'Roleplays and Scenario-Based Problem Solving. Lesson Design Labs. Peer Reflection Circles and Collaborative Planning.'),
((SELECT id FROM programs WHERE slug = 'bldea'), 'impact', 'Outcomes and Impact', '90% of teachers submitted revised lesson plans aligned to new practices. Higher ownership, clarity, and classroom strategy observed across cohorts. School leadership committed to ongoing mentoring circles and internal CPD.'),
((SELECT id FROM programs WHERE slug = 'bldea'), 'strategic_alignment', 'Strategic Alignment with BLDEA Goals', 'This initiative directly supported BLDEA''s commitment to: NEP 2020 Integration in Teaching Practice. Structured Professional Development for Staff. Improved Student Engagement through Active Methodologies. Internal Leadership Capacity through Peer Mentoring Models. Outcome-Based Approaches in Academic Delivery.'),
((SELECT id FROM programs WHERE slug = 'bldea'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'bldea'), 'conclusion', 'Turning Teachers into Changemakers', 'At BLDEA Schools, Rareminds didn''t just train teachers—we helped shift the culture of classrooms. By building both confidence and capability, our approach enabled teachers to become reflective practitioners who lead learning with clarity, care, and consistency. Together, we laid the foundation for a sustainable teaching excellence model rooted in purpose, pedagogy, and practice.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- =====================================================
-- NAAN MUDHALVAN CATEGORY PROGRAM SECTIONS
-- =====================================================

-- Insert program sections for Naan Mudhalvan 2024
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2024'), 'introduction', 'Introduction', 'Rareminds proudly partnered with the Tamil Nadu Skill Development Corporation (TNSDC) under the Naan Mudhalvan flagship initiative to transform technical education for Arts and Science students across Tamil Nadu. This program focused on delivering high-impact, project-based training in critical emerging technologies—bridging classroom theory with real-world practice. The partnership empowered students with future-ready skills, practical exposure, and the confidence to meet the demands of an evolving digital and industrial workforce.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2024'), 'about', 'About the Program', 'Through this collaboration, Rareminds delivered four specialized 45-hour experiential training programs to undergraduate students during the Even Semesters of the 2024–2025 academic year. These mandatory programs provided immersive, hands-on learning experiences in the following sectors: Chemical Safety in Battery Management, EV Battery Management Systems, Food Analysis Processing and Preservation, Organic Food Production. Each course blended in-person instruction with LMS-based support, enabling students to work on real-time simulations, hands-on projects, and practical applications from day one. The programs were designed to enhance both technical competencies and employability skills in alignment with industry expectations.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2024'), 'course_enrollment', 'Course Enrollment by University', 'Organic Food Practices - Total: 2,312 students across Bharathidasan University (1,056), Manonmaniam Sundranar University (569), Alagappa University (294), Madurai Kamaraj University (276), Mother Teresa University (117). Food Analysis Processing and Preservation - Total: 2,230 students across Periyar University (1,419), Annamalai University (589), Bharathiar University (222). Medical Coding - Total: 3,807 students across Thiruvalluvar University (1,532), Annamalai University (1,416), Madurai Kamaraj University (643), Mother Teresa University (216). Agri Business Management - Total: 2,449 students across Thiruvalluvar University (1,237), University of Madras (1,212).'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2024'), 'impact', 'Key Outcomes & Impact', '10,798 students were trained through structured, mentor-led sessions across partner universities in Tamil Nadu. All participants successfully completed comprehensive final projects, showcasing the practical application of their learning Evaluations were jointly conducted by college faculty and Rareminds'' industry experts. Where applicable, students actively participated in mandatory hackathons—fostering innovation, critical thinking, and collaborative problem-solving. Employability outcomes were strengthened through integrated support for placements, internships, and real-time project experiences. Institutional feedback from TNSDC and participating universities was overwhelmingly positive, noting higher student engagement, curiosity, and application-based learning.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2024'), 'strategic_alignment', 'Strategic Alignment with TNSDC Goals', 'Skill Development & Employability: Delivery of industry-aligned content enhanced the job readiness of Arts and Science graduates.

Curriculum Innovation: Courses introduced students to emerging technologies, aligning academic learning with evolving industry demands.

Student Engagement & Retention: Project-based methodologies significantly improved student interest, satisfaction, and knowledge retention.

Workforce Readiness: The initiative helped create a skilled talent pipeline in critical sectors supporting Tamil Nadu economic and industrial development.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2024'), 'video', 'Program Videos',              '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2024'), 'conclusion', 'Conclusion', 'The collaboration between Rareminds and TNSDC''s Naan Mudhalvan program stands as a model for impactful public–private partnerships in higher education. By turning traditional classrooms into hubs of innovation and applied learning, Rareminds empowered thousands of students to transition from passive learners to confident, industry-ready contributors across agriculture, food technology, and EV sectors. This partnership demonstrates how purposeful education reform can drive future-ready outcomes at scale.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Insert program sections for Naan Mudhalvan 2023
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2023'), 'introduction', 'Introduction', 'Rareminds proudly partnered with the Tamil Nadu Skill Development Corporation (TNSDC) under the Naan Mudhalvan flagship program to significantly enhance the technical education landscape for Arts and Science students across Tamil Nadu. This initiative focused on delivering high-impact, project-based training in critical emerging technologies, effectively bridging traditional classroom learning with practical, real-world applications. The collaboration equipped students with future-ready skills and the confidence essential for success in the evolving digital and industrial workforce.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2023'), 'about', 'About the Program', 'As part of this strategic collaboration, Rareminds delivered four specialized 45-hour experiential training programs to undergraduate students during the Even Semester of the 2023–2024 academic year. These mandatory courses were designed to provide hands-on experience and practical understanding in key sectors: Agribusiness Management, EV Battery Management, Food Analysis, Organic Food Production Techniques. Each program combined theoretical knowledge with practical application, enabling students to engage in comprehensive projects, simulations, and real-world problem-solving from day one. The curriculum included physical classroom interventions and supplementary LMS-based content, ensuring a dynamic and blended learning experience.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2023'), 'course_enrollment', 'Detailed Course Enrollment by University', 'Agribusiness Management - Total: 2,072 students across Alagappa University (296), Bharathidasan University (963), Madurai Kamaraj University (223), Mother Teresa University (93), Manonmaniam Sundaranar University (497).EV Battery Management - Total: 14,564 students across multiple universities including Periyar University (3,653), Thiruvalluvar University (2,541), Bharathidasan University (1,749), Annamalai University (1,651), University of Madras (1,472), Manonmaniam Sundaranar University (953), Bharathiar University (879), Madurai Kamaraj University (789), Alagappa University (632), Mother Teresa University (245). Food Analysis - Total: 1,637 students across Thiruvalluvar University (813), University of Madras (824).Organic Food Production Techniques - Total: 2,044 students across Periyar University (1,282), Annamalai University (541), Bharathiar University (221).'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2023'), 'impact', 'Key Outcomes & Impact', '20,317 students trained through structured, mentor-led sessions across various universities in Tamil Nadu. 100% of participants completed comprehensive final projects, demonstrating practical application of their learning Evaluations were conducted jointly by college faculty and Rareminds'' industry experts. High engagement in mandatory hackathons, wherever applicable, fostering innovation, critical thinking, and collaborative problem-solving. Strengthened employability outcomes, with integrated placement, internship, and hackathon support initiatives. Positive institutional feedback from TNSDC and partner universities, highlighting increased student engagement, curiosity, and application-based learning.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2023'), 'strategic_alignment', 'Strategic Alignment with TNSDC Goals', 'Skill Development & Employability: Delivery of industry-aligned content boosted the job-readiness of Arts and Science graduates.

Curriculum Innovation: Introduction of emerging technology domains aligned academic offerings with evolving industry needs.

Student Engagement & Retention: Project-based learning significantly increased student interest, satisfaction, and knowledge retention.

Workforce Readiness: The program nurtured a talent pipeline in sectors critical to Tamil Nadu socio-economic development.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2023'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2023'), 'conclusion', 'Conclusion', 'The successful collaboration between Rareminds and the TNSDC''s Naan Mudhalvan program demonstrated Rareminds'' proven capacity to deliver measurable impact, reimagine classroom learning, and align with both institutional and governmental priorities. By turning classrooms into active innovation spaces, Rareminds empowered thousands of students to transition from passive learners to confident contributors in the fields of technology, agriculture, and sustainability. This initiative remains a shining example of how public-private partnerships can reshape education for a future-ready India.')
ON CONFLICT (program_id, section_key) DO NOTHING;

-- Insert program sections for Naan Mudhalvan 4th sem 2025
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-4th-sem-2025'), 'introduction', 'Introduction', 'Rareminds partnered with the Tamil Nadu Skill Development Corporation (TNSDC) under the "Naan Mudhalvan" flagship initiative to transform technical education for Arts and Science students across Tamil Nadu. The program delivered high-impact, project-based training in emerging technologies, effectively bridging classroom theory with real-world application. It empowered students with future-ready skills, practical exposure, and the confidence to meet evolving industry demands.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-4th-sem-2025'), 'about', 'About the Program', '
 Rareminds delivered specialized 45-hour experiential training programs to undergraduate students during the 4th Semester of the 2024–2025 academic year. These mandatory programs offered immersive, hands-on learning in the following domains: Food Analysis, Processing and Preservation Techniques, Organic Food Production Techniques, Sustainability & Green Chemistry in EV Sector, Chemical Safety in Battery Management. The programs combined in-person instruction with LMS-based support, enabling students to engage in real-time simulations, projects, and practical applications from day one.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-4th-sem-2025'), 'course_enrollment', 'Detailed Course Enrollment by University', '1. Food Analysis, Processing and Preservation Techniques (4th Semester) - Total: 5,219 students across Periyar University (1,351), University of Madras (850), Thiruvalluvar University (929), Annamalai University (565), Manonmaniam Sundaranar University (555), Bharathiar University (323), Alagappa University (301), Madurai Kamaraj University (224), Mother Teresa University (121). 2. Organic Food Production Techniques (4th Semester) - Total: 991 students across Bharathidasan University (991). 3. Sustainability & Green Chemistry in EV Sector (4th Semester) - Total: 7,483 students across Bharathidasan University (1,693), Annamalai University (1,648), Thiruvalluvar University (1,550), Madurai Kamaraj University (878), Manonmaniam Sundaranar University (968), Alagappa University (516), Mother Teresa University (230). 4. Chemical Safety in Battery Management (4th Semester) - Total: 2,755 students across Alagappa University (572), Madurai Kamaraj University (893), Manonmaniam Sundaranar University (1,044), Mother Teresa University (246).'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-4th-sem-2025'), 'impact', 'Key Outcomes & Impact', '2,755 students trained on Chemical Safety in Battery Management Strong hands-on learning outcomes through mentor-led sessions and real-world applications. 100% project completion across all enrolled students, evaluated jointly by Master Assessor Faculty and Rareminds'' industry experts. 70%+ student participation in mandatory hackathons promotes innovation, collaboration, and problem-solving. Enhanced employability through post-training support, including placement drives and internship opportunities, targeting at least 25% placement conversion. Positive feedback from TNSDC and universities citing better engagement, curiosity, and practical understanding among students Large-scale implementation across leading universities.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-4th-sem-2025'), 'strategic_alignment', 'Strategic Alignment with TNSDC Goals', 'Skill Development & Employability: Delivered industry-relevant, practical skills.

Curriculum Innovation: Introduced cutting-edge, policy-aligned programs.

Student Engagement: Strengthened participation through experiential learning.

Workforce Readiness: Built a pipeline of skilled graduates.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-4th-sem-2025'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-4th-sem-2025'), 'conclusion', 'Conclusion', 'The Rareminds–TNSDC collaboration under the Naan Mudhalvan initiative demonstrates strong industry-academia synergy. By combining innovation, hands-on learning, and outcome-driven delivery, Rareminds enabled thousands of students to transition into confident, future-ready professionals.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Insert program sections for Naan Mudhalvan 6th sem 2025
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-6th-sem-2025'), 'introduction', 'Introduction', ' Rareminds partnered with the Tamil Nadu Skill Development Corporation (TNSDC) under the "Naan Mudhalvan" flagship initiative to enhance technical education for Arts and Science students across Tamil Nadu. The program focused on delivering project-based training in emerging technologies, bridging academic learning with practical industry application.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-6th-sem-2025'), 'about', 'About the Program', ' Rareminds delivered a specialized 45-hour experiential training program during the 6th Semester of the 2024–2025 academic year. These mandatory programs provided immersive, hands-on learning experiences in the following sector : EV Battery Management System. The program combined in-person sessions with LMS-enabled learning, allowing students to work on simulations, projects, and practical applications from the outset.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-6th-sem-2025'), 'course_enrollment', 'Detailed Course Enrollment by University', '1. EV Battery Management System (6th Semester) - Total: 5,198 students across Annamalai University (1,811), Thiruvalluvar University (1,740), Bharathidasan University (1,647).'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-6th-sem-2025'), 'impact', 'Key Outcomes & Impact', '7,953 students trained on EV Battery Management System. 100% project completion evaluated by experts Implementation across major universities' '70%+ student participation in mandatory hackathons promotes innovation, collaboration, and problem-solving. Improved employability through placements and internships. Positive feedback from TNSDC and universities citing better engagement, curiosity, and practical understanding among students.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-6th-sem-2025'), 'strategic_alignment', 'Strategic Alignment with TNSDC Goals', 'Innovation & Learning Approach: By integrating innovation, hands-on learning, and outcome-driven models, Rareminds enhanced the overall learning experience.

Student Transformation: Helped thousands of students transition from passive learners to future-ready professionals.

Scalable Impact: This program stands as a scalable model for education transformation and skill empowerment across India.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-6th-sem-2025'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-6th-sem-2025'), 'conclusion', 'Conclusion', 'The Rareminds–TNSDC collaboration under the Naan Mudhalvan initiative highlights the effectiveness of large-scale, outcome-driven training. By equipping students with practical skills and industry exposure, the program strengthened workforce readiness and created a scalable model for education transformation.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Insert program sections for Naan Mudhalvan 2025
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2025'), 'introduction', 'Introduction', 'Rareminds proudly partnered with the Tamil Nadu Skill Development Corporation (TNSDC) under the "Naan Mudhalvan" flagship initiative to transform technical education for Arts and Science students across Tamil Nadu. This program focused on delivering high-impact, project-based training in critical emerging technologies—bridging classroom theory with real-world practice. The partnership empowered students with future-ready skills, practical exposure, and the confidence to meet the demands of an evolving digital and industrial workforce.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2025'), 'about', 'About the Program', 'Through this collaboration, Rareminds delivered five specialized 45-hour experiential training programs to undergraduate students during the Odd Semester (5th) of the 2025–2026 academic year. These mandatory programs provided immersive, hands-on learning experiences in the following sectors: Good Manufacturing Practices, Medical Coding, Food Safety and Quality Management. The courses blended in-person classes with LMS-based support, enabling students to work on real-time simulations, projects, and practical applications from day one.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2025'), 'course_enrollment', 'Detailed Course Enrollment by University', '1. Medical Coding (5th Semester) - Total: 3,886 students across Periyar University (2,987), Bharathiar University (899). 2. GMP (5th Semester) - Total: 5,049 students across Periyar University (2,148), Manonmaniam Sundaranar University (949), Madurai Kamaraj University (797), Alagappa University (508), Bharathiar University (420), Mother Teresa University (227). 3. Food Safety and Quality Management (5th Semester) - Total: 5,560 students across Periyar University (1,283), Thiruvalluvar University (888), Bharathidasan University (868), Annamalai University (556), University of Madras (557), Manonmaniam Sundaranar University (540), Bharathiar University (301), Alagappa University (292), Madurai Kamaraj University (157), Mother Teresa University (118).'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2025'), 'impact', 'Objectives', '14,495 students to be trained through hands-on, mentor-led sessions across major Tamil Nadu universities. 100% project completion across all enrolled students, evaluated jointly by Master Assessor Faculty and Rareminds'' industry experts. 70%+ student participation in mandatory hackathons promotes innovation, collaboration, and problem-solving. Enhanced employability through post-training support, including placement drives and internship opportunities, targeting at least 25% placement conversion. Positive feedback from TNSDC and universities citing better engagement, curiosity, and practical understanding among students.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2025'), 'strategic_alignment', 'Strategic Alignment with TNSDC Goals', 'Skill Development & Employability: Provide students with industry-relevant, practical skills.

Curriculum Innovation: Introduce cutting-edge topics aligned with national education policy.

Student Engagement: Elevate learning interest through experiential pedagogy.

Workforce Readiness: Create a pipeline of skilled graduates prepared for high-demand industries.'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2025'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'naan-mudhalvan-2025'), 'conclusion', 'Conclusion', 'The Rareminds–TNSDC collaboration under the Naan Mudhalvan initiative exemplifies impactful industry-academia synergy. By integrating innovation, hands-on learning, and outcome-driven models, Rareminds helped thousands of students transition from passive learners to future-ready professionals. This program stands as a scalable model for education transformation and skill empowerment across India.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- =====================================================
-- GOVERNMENT BODY CATEGORY PROGRAMS
-- =====================================================



-- =====================================================
-- GOVERNMENT BODY CATEGORY PROGRAM SECTIONS
-- =====================================================

-- Insert program sections for Tripura
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'tripura'), 'introduction', 'Equipping Candidates for Global Careers with Confidence & Clarity', 'Overseas job interviews demand more than just qualifications — they require candidates to present themselves with poise, adapt to cross-cultural environments, and navigate high-stakes conversations effectively. Tripura Skill Development Corporation (TSDC) identified the need to prepare aspiring overseas placement candidates with focused, practical training that would address both interview performance and communication competency. A targeted approach was implemented to ensure that participants — ranging from ITI graduates to young professionals — received actionable strategies, hands-on practice, and cross-cultural readiness for international job markets. Rareminds, under the leadership of CEO Dr. Subhashini, delivered a structured 10-hour training program designed to build both competence and confidence. Dr. Subhashini personally conducted the sessions, bringing strategic insights and real-world experience directly to participants.'),
((SELECT id FROM programs WHERE slug = 'tripura'), 'programs', 'Program Delivery', 'Total Training Hours: 10 hours. Schedule: 2 hours/day across 5 days. Participants Trained: 200 candidates (Two batches of 100 each). Participant Profile: ITI, Diploma, Graduates, Postgraduates, Young Professionals. Trainer: Dr. Subhashini, CEO, Rareminds.'),
((SELECT id FROM programs WHERE slug = 'tripura'), 'modules', 'Modules Covered', 'Interview Skills: Effective Resume and Cover Letter Writing, Common Interview Questions & Best Practices, Non-verbal Communication & Body Language, Handling Difficult Questions & Stress Management, Mock Interviews with Personalized Feedback. Cross-cultural Communication: Understanding Cultural Differences and Sensitivities, Communication Strategies for Diverse Audiences, Global Business Etiquette, Intercultural Conflict Resolution & Negotiation.'),
((SELECT id FROM programs WHERE slug = 'tripura'), 'approaches', 'Multiple Approaches', 'Interactive Presentations & Case Studies. Group Discussions & Peer Activities. Roleplays & Interview Simulations. Individualized Coaching & Feedback.'),
((SELECT id FROM programs WHERE slug = 'tripura'), 'impact', 'Outcomes and Impact', '95% participants reported improved confidence in handling interviews. 92% demonstrated better articulation in mock interview evaluations. 87% showed improvement in cross-cultural awareness and etiquette. 100% of participants completed mock interviews with personalized feedback. Post-training self-assessment scores improved by an average of 40% across key skill areas. Participant feedback emphasized high satisfaction with the hands-on approach, real-world relevance, and the opportunity to practice in simulated interview environments.'),
((SELECT id FROM programs WHERE slug = 'tripura'), 'strategic_alignment', 'Strategic Alignment with TSDC Goals', 'This initiative directly supported TSDC''s mission to strengthen global employability for regional youth, bridge skill gaps through targeted communication and interview training, prepare candidates for diverse cultural and professional environments, and enhance placement success rates through practical readiness.'),
((SELECT id FROM programs WHERE slug = 'tripura'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'tripura'), 'conclusion', 'Turning Aspirants into Global Professionals', 'Through this focused intervention, Rareminds — under the direct leadership and facilitation of CEO Dr. Subhashini — empowered Tripura''s overseas placement aspirants with the tools, confidence, and global readiness essential for success. The program served not only as a skill-building platform but also as a mindset transformation, directly contributing to TSDC''s vision of creating globally competitive talent.')
ON CONFLICT (program_id, section_key) DO NOTHING;
-- Insert program sections for TNSDC ITI (Spoken English)
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'tnsdc-iti-spoken-english'), 'introduction', 'Introduction', 'Rareminds partnered with Tamil Nadu Skill Development Corporation (TNSDC) to improve English and personality development among students in government welfare hostels. This was hands-on training that equipped students with critical communication skills and confidence for their future academic and professional life.'),
((SELECT id FROM programs WHERE slug = 'tnsdc-iti-spoken-english'), 'about', 'About the Program', 'English & Personality Development: A full English and Personality Development program was offered to 2nd and 3rd year students in Tribal, ADW, BC, MBC, DNC, and Minorities Welfare Department Hostels.

Learning & Assessment: The curriculum used open-source documentary movies for listening/speaking practice, English newspapers for reading/writing, and dedicated workbooks for structured assessments. Cambridge University administered pre- and post-training exams to monitor student progress and track improvement on the CEFR scale.'),
((SELECT id FROM programs WHERE slug = 'tnsdc-iti-spoken-english'), 'impact', 'Key Outcomes & Impact', 'Trained 10,210 students over 7 Months on English communication and personal development skills. The program was offered in 7 districts of Tamil Nadu (Nammakkal, Coimbatore, Tiruppur, Nilgiris, Erode, Salem, and Karur) in 90+ hostels. The program was delivered by 150+ trainers. Core Competencies: Students improved their basic English, conversational skills, and reading comprehension. Cambridge assessments are at the heart of Rareminds'' outcome-driven approach, which is about measurable improvement (at least one CEFR level up) The following are the grades as assessed by Cambridge. 52.14% of students achieved A2, indicating strong foundational English proficiency post-training. 6.84% of students reached B1, showing above-basic competence and readiness for workplace communication. 6.84% of students remained at A1, suggesting emerging skills that need continued support. 0.85% improved from A1 to A2, demonstrating upward growth. 0.85% progressed from A2 to B1, showing measurable advancement.'),
((SELECT id FROM programs WHERE slug = 'tnsdc-iti-spoken-english'), 'strategic_alignment', 'Strategic Alignment with TNSDC & Government Goals', 'The initiative supported TNSDC and the Government of Tamil Nadu''s key objectives: Empowering underprivileged students by training life and communication skills in Tribal, ADW, BC, MBC, DNC, and Minority welfare hostels. Better job prospects and social integration by building students'' confidence and communication skills, which will lead to better future opportunities. Cambridge University Press ensures accountability and quality assurance through independent standardized assessments to measure learning outcomes. Practical English for daily use and future opportunities, not just academic proficiency.'),
((SELECT id FROM programs WHERE slug = 'tnsdc-iti-spoken-english'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'tnsdc-iti-spoken-english'), 'conclusion', 'Building Lasting Confidence', 'Rareminds delivers measurable impact in English communication and personality development across diverse learner groups. By aligning with the government''s student empowerment goals, Rareminds focuses on practical, confidence-building interventions grounded in the CEFR framework, ensuring structured and outcome-driven progress. While rote learning has its place in foundational skill-building, Rareminds integrates it with real-world communication strategies to foster both accuracy and fluency. Students gain the ability to apply language meaningfully—in interviews, group settings, and digital communication. The program is adaptable, culturally relevant, and designed to support lifelong language confidence across regions and learner levels.')
ON CONFLICT (program_id, section_key) DO NOTHING;

-- Insert program sections for TNSDC Schools
INSERT INTO program_sections (program_id, section_key, title, content) VALUES

((SELECT id FROM programs WHERE slug = 'tnsdc-schools'), 
'introduction', 
'Introduction', 
'Rareminds, in a significant partnership with the Tamil Nadu Skill Development Corporation, recently concluded a transformative 7-day (45-hour) vocational training program across 121 Government Higher Secondary Schools (GHSS). This initiative was designed to empower 12th-grade (2nd PUC) students with tangible, in-demand skills, paving the way for entrepreneurship and enhancing employability in key growth sectors.'),

((SELECT id FROM programs WHERE slug = 'tnsdc-schools'), 
'about', 
'About the Program', 
'The program successfully reached 1,974 students students allocated by the Tamil Nadu Skill Development Corporation, demonstrating Rareminds'' expertise in large-scale, impactful educational delivery. The 7-day engagement offered students two distinct, yet equally valuable, vocational pathways: Cloud Kitchen Operations: Encouraging the Entrepreneur This stream was designed to give students a comprehensive understanding of the burgeoning cloud kitchen industry, equipping them with the knowledge to launch and manage their food ventures. Agri-Food Processing & Preservation: Cultivating Skills and Opportunities This comprehensive 40-hour curriculum equips students with vital knowledge of the agri-food industry, focusing on practical ways to enhance food value, improve safety standards, and extend shelf life.'),

((SELECT id FROM programs WHERE slug = 'tnsdc-schools'), 
'impact', 
'Key Outcomes & Impact', 
'The program was implemented across 121 Government Higher Secondary Schools (GHSS). 1,974 students were successfully trained. Five Villupuram schools successfully implemented the Cloud Kitchen entrepreneurship program, training 76 aspiring food entrepreneurs. The Agri-Food Processing & Preservation program was implemented in 116 schools, where 1,570 students gained practical skills and knowledge and started their home business. Students gained hands-on experience through activities such as canning, bottling, pickling, fermentation, drying, and freezing techniques. Students were introduced to food safety principles, hygiene practices, HACCP basics, and quality control measures. Students who started business registered under FSSAI.'),

((SELECT id FROM programs WHERE slug = 'tnsdc-schools'), 
'strategic_alignment', 
'Strategic Alignment with TNSDC Goals', 
'This initiative supported key institutional objectives such as: Effortless Enterpreneurship alignment through skill-based, experiential learning integration. Enhanced student employability with practical, in-demand skills and entrepreneurship training. Future-proof curriculum in high-growth sectors like food technology and entrepreneurship. Proven government partnership ensuring reliable implementation of large-scale programs. Fully integrated program delivery reducing administrative burden for institutions. Measurable impact through structured reporting and feedback on student skills and confidence.'),
  
((SELECT id FROM programs WHERE slug = 'tnsdc-schools'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),

((SELECT id FROM programs WHERE slug = 'tnsdc-schools'), 
'conclusion', 
'Conclusion', 
'This successful GHSS project underscores Rareminds'' dedication to delivering high-quality, large-scale vocational training in collaboration with government bodies. By empowering nearly 2,000 students with practical knowledge and entrepreneurial insights, we are actively shaping a more skilled, confident, and future-ready generation.')
ON CONFLICT (program_id, section_key) DO NOTHING;

-- Note: AICTE and KSDC have no sections in frontend data, so no program_sections entries are added for them.



-- =====================================================
-- GLOBAL INTERNATIONAL SCHOOL PROGRAM SECTIONS
-- =====================================================

-- Insert program sections for Global International School
INSERT INTO program_sections (program_id, section_key, title, content) VALUES
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'introduction', 'Global International School – Empowering Teachers', 'From Content Delivery to Classroom Impact in 2 Days. Teachers shape the learning environment, but they can only transform classrooms when they are equipped and inspired. However, most lacked structured exposure to NEP-aligned pedagogy, meaningful technology integration, and effective strategies to manage young, modern learners. The shift from traditional instruction to learner-centric approaches demanded more than content knowledge. It required mindset shifts, new tools, and practical strategies. Yet, most training programs remained too theoretical or generic to create lasting change. Rareminds was invited to bridge this critical gap with focused, hands-on capacity-building for today''s classrooms.'),
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'inventions', 'Rareminds Intervention', 'In November 2023, Rareminds conducted a 2-day intensive capacity-building program for 40 teachers at Global International School. Led by 3 expert master trainers, the sessions blended foundational understanding with practical application.'),
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'modules', 'Modules Covered', 'Contemporary Education and Classroom Skills. Digital Tools for Teaching. Creating a Feedback Culture. Student Engagement Based on Learner Profiles. Activity-Based Teaching Modules. Personalized Reflection and Action Planning.'),
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'approaches', 'Multiple Approaches', 'Interactive Group Activities and Demos. Peer Discussions and Application Circles. Micro-Innovation Planning for Classroom Practice.'),
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'impact', 'Outcomes and Impact', '100% participation and engagement across all sessions. Teachers developed classroom innovation plans post-training. Improved lesson planning confidence and use of engagement tools.'),
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'strategic_alignment', 'Strategic Alignment with Global International School Goals', 'This initiative directly supported the school''s goals around: Teacher Capacity Building and NEP Integration. Rapid Upskilling with Practical Teaching Tools. Personalized Classroom Innovation Initiatives. Enhanced Student Engagement and Retention.'),
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'video', 'Program Videos', '[{"item1":"/video1.mp4","item2":"/video2.mp4","item3":"/video3.mp4"}]'),
((SELECT id FROM programs WHERE slug = 'global-international-school'), 'conclusion', 'Conclusion: Turning Educators into Enablers', 'At Global International School, Rareminds supported teachers to go beyond delivery. By equipping them with modern strategies, tech tools, and learner-focused frameworks, we helped lay the groundwork for classrooms that are engaging, inclusive, and impact-driven. It was more than training—it was a catalyst for everyday transformation.')
ON CONFLICT (program_id, section_key) DO NOTHING;

-- =====================================================
-- END OF SEED FILE
-- =====================================================
-- Total Programs: 17
-- Total Categories: College, University, Naan Mudhalvan, Government Body, School
-- =====================================================