export const projects = [
  
  {
   id: '1',
    name: 'Acharya',
    description: 'Rareminds trained 700+ MBA, MCA, and Physiotherapy students in communication and placement skills, boosting interview confidence and job readiness.',
    category: 'College',
    status: '',
    year: '2023',
    location: 'Karnataka',
    technologies: [],
    imageUrl: 'https://www.campusoption.com/images/articles/06_06_19_073632_acharya-institute-of-technology.jpg',
    timeline: 'May 2023',
  },
   {
   id: '2',
    name: 'PES',
    description: 'The Rareminds Bootcamp at PES Engineering College, Mandya delivered a 45-hour hands-on web development program, transforming students into confident, industry-ready developers',
    category: 'College',
    status: 'Active',
    year: '2025',
    location: 'Karnataka',
    technologies: [],
    imageUrl: '/academy/Projects/pes.png',
    timeline: 'July 2023',
  },
  {
   id: '3',
     name: 'BLDEA',
    description: 'Rareminds conducted a 3-day intensive program for 200+ BLDEA teachers, delivering hands-on, NEP-aligned training to strengthen pedagogy, mindset, and classroom effectiveness.',
    category: 'Organization',
    status: '',
    year: '2023',
    location: 'Karnataka',
    technologies: [],
    imageUrl: '/academy/Projects/BLDEA.png',
    timeline: 'Nov 2023',
  },
  {
    id: '4',
    name: 'Naan Mudhalvan 2024 Upskilling Program (Powered by Rareminds)',
    description: 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.',
    category: 'Naan Mudhalvan',
    status: 'Active',
    year: '2024',
    location: 'TamilNadu',
    technologies: ['React', 'Node.js', 'TensorFlow', 'MongoDB'],
    imageUrl: '/academy/Projects/nanmudhalvan.jpg',
    timeline: 'Jul 2024',
  },
   {
    id: '5',
    name: 'Tripura',
    description: 'Rareminds trained 200 overseas candidates via a CEO-led intensive, boosting interview confidence and global readiness in line with Tripura Skill Development Mission.',
    category: 'Government Body',
    status: 'Completed',
    year: '2024',
    location: 'Tripura',
    technologies: [],
    imageUrl: '/academy/Projects/tripura.png',
    timeline: 'Jan 2024',
  }
,
  {
    id: '6',
    name: 'TNSDC ITI (Spoken English)',
    description: 'Rareminds partnered with TNSDC to train government hostel students in English, communication, and confidence.',
    category: 'Government Body',
    status: 'Completed',
    year: '2024',
    location: 'TamilNadu',
    technologies: [],
    imageUrl: 'https://www.pkrarts.org/wp-content/uploads/2018/01/tnsdc.png',
    timeline: 'Feb 2024',
  }
,
{
    id: '7',
    name: 'TNSDC Schools',
    description:'Rareminds delivered a 7-day training across 121 schools, empowering 1,974 students with employability skills.',
    category: 'Government Body',
    status: 'Completed',
    year: '2024',
    location: 'TamilNadu',
    technologies: [],
    imageUrl: 'https://www.pkrarts.org/wp-content/uploads/2018/01/tnsdc.png',
    timeline: 'Apr 2024',
}
,
  {
    id: '8',
    name: 'Naan Mudhalvan 2023 Upskilling Program (Powered by Rareminds)',
    description: 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.',
    category: 'Naan Mudhalvan',
    status: 'Completed',
    year: '2023',
    location: 'TamilNadu',
    technologies: ['Vue.js', 'Python', 'D3.js', 'MySQL'],
    imageUrl: '/academy/Projects/nanmudhalvan.jpg',
    timeline: 'Jan 2023',
  },
  
  
  {
    id: '9',
    name: 'Naan Mudhalvan 4th sem 2025 Upskilling Program (Powered by Rareminds)',
    description: 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.',
    category: 'Naan Mudhalvan',
    status: 'Active',
    year: '2025',
    location: 'TamilNadu',
    technologies: ['React', 'Node.js', 'TensorFlow', 'MongoDB'],
    imageUrl: '/academy/Projects/nanmudhalvan.jpg',
    timeline: 'Jan 2025',
  },
   {
    id: '10',
    name: 'Naan Mudhalvan 6th sem 2025 Upskilling Program (Powered by Rareminds)',
    description: 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.',
    category: 'Naan Mudhalvan',
    status: 'Active',
    year: '2025',
    location: 'TamilNadu',
    technologies: ['React', 'Node.js', 'TensorFlow', 'MongoDB'],
    imageUrl: '/academy/Projects/nanmudhalvan.jpg',
    timeline: 'Jan 2025',
  },
 {
    id: '11',
    name: 'VELS',
    description: 'Rareminds delivered project-based training at VELS University, bridging classroom learning with real-world skills for first-year students.',
    category: 'College',
    status: 'Completed',
    year: '2024',
    location: 'TamilNadu',
    technologies: [],
    imageUrl: '/academy/Projects/vels.png',
    timeline: 'March 2025',
  }
  ,

  

 {
    id: '12',
    name: 'Naan Mudhalvan 2025 Upskilling Program (Powered by Rareminds)',
    description: 'Rareminds partnered with TNSDC under Naan Mudhalvan to deliver project-based training in emerging technologies for Arts and Science students.',
    category: 'Naan Mudhalvan',
    status: 'Active',
    year: '2025',
    location: 'TamilNadu',
    technologies: ['React', 'Node.js', 'TensorFlow', 'MongoDB'],
    imageUrl: '/academy/Projects/nanmudhalvan.jpg',
    timeline: 'july 2025 - Present',
  },

  {
    id: '13',
    name: 'AICTE',
    description: 'Rareminds partnered with All India Council for Technical Education to deliver industry-focused, experiential programs that build job-ready skills and confidence',
    category: 'Government Body',
    status: 'Completed',
    year: '2025',
    location: 'Pan India',
    technologies: [],
    imageUrl: '/academy/Projects/aicte.png',
    timeline: 'UpComing',
  },
  {
    id: '14',
    name: 'KSDC',
    description: '',
    category: 'Government Body',
    status: 'In Progress',
    university: 'VTU',
    year: '2025',
    location: 'Karnataka',
    technologies: [],
    imageUrl: '/academy/Projects/ksdc.png',
    timeline: 'UpComing',
  },

 {
    id: '15',
    name: 'Visvesvaraya Technological University',
    description: '',
    category: 'College',
    status: 'Active',
    year: '2025',
    location: 'Karnataka',
    technologies: ['React', 'Node.js', 'TensorFlow', 'MongoDB'],
    imageUrl: '/academy/Projects/vtu.png',
    timeline: 'UpComing',
  },
  
  {
   id: '16',
    name: 'Global International School ',
    description: 'Rareminds bridged gaps in traditional teacher training by delivering hands-on, NEP-aligned programs that equipped educators with practical skills, modern tools, and learner-centric strategies.',
    category: 'School',
    status: '',
    year: '2023',
    location: 'Karnataka',
    technologies: [],
    imageUrl: '/academy/Projects/school.png',
    timeline: 'Nov 2023',
  },
  {
   id: '17',
    name: 'DSATM',
    description: 'Rareminds partnered with DSATM to deliver career-focused training that equipped students with technical and soft skills for professional success.',
    category: 'College',
    status: '',
    year: '2019',
    location: 'Karnataka',
    technologies: [],
    imageUrl: '/academy/Projects/dsatm.png',
    timeline: 'Oct-Nov 2019',
  },
];