// utils/testimonialData.ts

export interface Testimonial {
  id: number;
  name: string;
  role?: string;  // We can use role or university/college here
  message: string;
}

export const testimonialsdata: Testimonial[] = [
  {
    id: 1,
    name: 'Praveen Kumar V',
    message: 'Excellent! This program provides valuable guidance for the future.',
    role: 'Vels',
  },
  {
    id: 2,
    name: 'M. Ismayil',
    message: 'It was very helpful in understanding key concepts. The teaching and explanation were nice and clear.',
    role: 'Vels',
  },
  {
    id: 3,
    name: 'K Syed Abdul Rehman',
    message: 'The trainer was most engaging with us and delivered the content beautifully. Most of the content helps us learn something new and will be helpful for our future endeavours.',
    role: 'Vels',
  },
  {
    id: 4,
    name: 'Mohammed Irfaan',
    message: 'Helpful and provided nice teaching and explanation.',
    role: 'Vels',
  },
  {
    id: 5,
    name: 'S. Vaishnavi',
    message: 'This full stack development training is very useful for our future careers.',
    role: 'Vels',
  },
  {
    id: 6,
    name: 'Mohan Krishnan',
    message: "It's very helpful for our job opportunities and enhancing our skills.",
    role: 'Vels',
  },
  {
    id: 7,
    name: 'K. Sandhiya',
    message: 'Excellent... A good teacher leading good training.',
    role: 'Vels',
  },
  {
    id: 8,
    name: 'K. Yogeshwaram',
    message: 'It was a very helpful and excellent adventure in class. I learnt some future technical subjects that will be useful for my future.',
    role: 'Vels',
  },
  {
    id: 9,
    name: 'Khadija Mohamed Meera Shahib',
    message: 'Gained valuable insights into organic farming that we weren’t aware of. It encouraged us to start organic farming in urban areas or on our terrace. A very informative session.',
    role: 'Bharathidasan University',
  },
  {
    id: 10,
    name: 'MUJAHITHA A',
    message: 'This course was very useful and gave us in-depth knowledge about organic production. The trainer was excellent.',
    role: 'Aiman College of Arts and Science for Women',
  },
  {
    id: 11,
    name: 'Asra Fathima S',
    message: 'Our trainer was excellent—his clear explanations and teaching style really deepened our understanding.',
    role: 'Thiruvalluvar University',
  },
  {
    id: 12,
    name: 'Manisha M.M',
    message: 'There’s so much to learn in organic farming. This course developed our skills and knowledge—it really motivated us to pursue farming and cultivation.',
    role: 'Muslim Arts College',
  },
  {
    id: 13,
    name: 'P. Kaviyarasan',
    message: 'The classes were helpful and easy to understand. They definitely increased our subject knowledge.',
    role: 'Arignar Anna Government Arts College, Musiri',
  },
  {
    id: 14,
    name: 'Karthik S',
    message: 'We greatly appreciate your commitment to creating a positive and inclusive classroom environment.',
    role: 'Bharathidasan University',
  },
  {
    id: 15,
    name: 'Varsha I S Siva Sankari',
    message: 'The class was both informative and engaging. The breaks and presentations helped maintain focus and visualized the concepts well.',
    role: 'Manonmaniam Sundaranar University',
  },
  {
    id: 16,
    name: 'Gopika M',
    message: 'The session was informative and well-structured. We learned a lot about organic production through engaging presentations.',
    role: 'Manonmaniam Sundaranar University',
  },
  {
    id: 17,
    name: 'A. Arul Vinya',
    message: 'I really liked this program. Organic farming is so relevant now, and the course inspired me to pursue it further. Thank you!',
    role: 'Manonmaniam Sundaranar University',
  },
  {
    id: 18,
    name: 'Karpagam A',
    message: 'The training was useful and informative. I learned a lot about organic food production. Thank you for this great opportunity.',
    role: 'Manonmaniam Sundaranar University',
  },
  {
    id: 19,
    name: 'S.A. Shershika',
    message: 'The program was excellent—interesting, useful, and very relevant to our studies. Thank you for organizing it.',
    role: 'Arunachala Arts and Science (Women) College',
  },
  {
    id: 20,
    name: 'M. Abinaya',
    message: 'I liked the way they taught organic food production. It helped me understand its benefits and deepened my knowledge.',
    role: 'Bharathidasan University',
  },
  {
    id: 21,
    name: 'V. Pavithra',
    message: 'We’re grateful for the inclusive and encouraging classroom environment you created.',
    role: 'Government Arts & Science College for Women, Bargur',
  },
  {
    id: 22,
    name: 'Kowsalya K',
    message: 'The trainers were supportive and experienced. Their guidance and feedback were really valuable.',
    role: 'Thanthai Periyar Government Arts and Science College - Autonomous',
  },
  {
    id: 23,
    name: 'Ajith',
    message: 'Medical coding has been an eye-opener for me. The sessions were informative and I’m grateful to the trainer for making it easy to understand.',
    role: 'Annamalai University',
  },
  {
    id: 24,
    name: 'Priya Dharshini',
    message: 'This program has greatly expanded my knowledge. Learning about sustainable farming in the agricultural sector was especially valuable.',
    role: 'Thiruvalluvar University',
  },
  {
    id: 25,
    name: 'Jagadeeshwaran',
    message: 'I gained insights into natural farming techniques, which I believe are crucial for a healthier future.',
    role: 'Madurai Kamaraj University',
  },
  {
    id: 26,
    name: 'Priya Raj Narayanan',
    message: 'The sessions helped me think critically about food safety and its real-world applications. It was more than just theory.',
    role: 'Mother Teresa Women’s University',
  },
  {
    id: 27,
    name: 'Monisha S',
    message: 'This course introduced me to a new way of understanding agriculture — practical, modern, and highly relevant.',
    role: 'Madurai Kamaraj University',
  },
  {
    id: 28,
    name: 'Sowmya R',
    message: 'Learning about organic farming methods was not only interesting but also inspiring. It has motivated me to consider a career in this field.',
    role: 'Thiruvalluvar University',
  },
  {
    id: 29,
    name: 'Jebamalar D',
    message: 'I truly appreciated the clarity of the content and how each topic was broken down. The training sessions were well-paced and engaging.',
    role: 'Mother Teresa Women’s University',
  },
  {
    id: 30,
    name: 'Malathi M',
    message: 'The course content was relevant, and I could relate it to my own academic background. It definitely boosted my confidence.',
    role: 'Annamalai University',
  },
  {
    id: 31,
    name: 'M. Perinbammal',
    message: 'This course gave me fresh perspectives on how food is produced, analyzed, and managed in the industry today.',
    role: 'Thiruvalluvar University',
  },
  {
    id: 32,
    name: 'M. Tamilselvi',
    message: 'Each topic in the program was clearly explained, and the PowerPoint materials made learning easier. The trainer’s approach was very effective.',
    role: 'Madurai Kamaraj University',
  },
  {
    id: 33,
    name: 'Keerthana L',
    message: 'I found the hands-on examples and real-life applications of agricultural business management very enlightening.',
    role: 'Mother Teresa Women’s University',
  },
  {
    id: 34,
    name: 'Maniram',
    message: 'This training was structured very well. I now understand how organic food production can be implemented commercially.',
    role: 'Thiruvalluvar University',
  },
  {
    id: 35,
    name: 'Sakthi',
    message: 'The sessions on organic farming were not only informative but also made me reflect on how agriculture impacts health and the environment.',
    role: 'Annamalai University',
  },
  {
    id: 36,
    name: 'L.A. Brunelcy Shynaba',
    message: 'I never thought I would enjoy a session on food analysis so much. The trainer kept it interactive and full of real-world examples.',
    role: 'Annamalai University',
  },
  {
    id: 37,
    name: 'Gunashleelan',
    message: 'The course gave me the confidence to explore opportunities in medical coding, which I hadn\'t considered before.',
    role: 'Thiruvalluvar University',
  },
  {
    id: 38,
    name: 'Venkatesh',
    message: 'From pest control to crop selection, I learned a lot of techniques that will help me in my agricultural studies.',
    role: 'Mother Teresa Women’s University',
  },
  {
    id: 39,
    name: 'Deepika P',
    message: 'This course on food safety and nutrition helped me realize the importance of quality control in the food industry.',
    role: 'Madurai Kamaraj University',
  },
  {
    id: 40,
    name: 'Selvanayagi S',
    message: 'What stood out was how accessible the topics were, even the complex ones. The trainer made sure we understood every step.',
    role: 'Annamalai University',
  },
  {
    id: 41,
    name: 'Manoranjini',
    message: 'The agri-business topics were fascinating, and the course introduced me to new career paths I hadn\'t thought of before.',
    role: 'Madurai Kamaraj University',
  },
  {
    id: 42,
    name: 'Archana',
    message: 'Food analysis is a topic I used to find boring, but this course changed that with its real-time examples and discussions.',
    role: 'Thiruvalluvar University',
  },
  {
    id: 43,
    name: 'Jagadeeshwaran',
    message: 'The trainer made the subject easy to grasp, even for students from non-science backgrounds. That’s something I really appreciated.',
    role: 'Madurai Kamaraj University',
  },
  {
    id: 44,
    name: 'P. Manoranjini',
    message: 'We were encouraged to ask questions and think beyond the textbook. I found the entire approach refreshing.',
    role: 'Mother Teresa Women’s University',
  },
  {
    id: 45,
    name: 'R. Sangeetha',
message: 'The sessions were very relevant to our current studies and future jobs. It was one of the best training experiences I’ve had.',
role: 'Thiruvalluvar University',
},
{
id: 46,
name: 'S. Nivetha',
message: 'I liked how the course was structured with a balance between theory and practical examples. It kept me interested throughout.',
role: 'Madurai Kamaraj University',
},
{
id: 47,
name: 'Shreya S',
message: 'The training on organic farming opened my eyes to sustainable practices that I can use in my own backyard.',
role: 'Thiruvalluvar University',
},
{
id: 48,
name: 'K. Krithika',
message: 'The course content was well organized and delivered. I feel more confident about pursuing a career in agricultural sciences now.',
role: 'Mother Teresa Women’s University',
},
{
id: 49,
name: 'Deepika',
message: 'This training provided practical knowledge that textbooks often miss. I feel better prepared for real-world challenges.',
role: 'Madurai Kamaraj University',
},
{
id: 50,
name: 'Ajith',
message: 'Medical coding training was eye-opening and has encouraged me to consider this as a career option.',
role: 'Annamalai University',
},
];
